In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("bikebuyer1.csv")

In [3]:
df.head()

ID Marital Status  Gender  Yearly Income  Children        Education  \
0  22711.0         Single    Male          30000       0.0  Partial College   
1  13555.0        Married  Female          40000       0.0  Graduate Degree   
2      NaN        Married    Male         160000       5.0  Partial College   
3      2.0         Single    Male         160000       0.0  Graduate Degree   
4  25410.0            NaN  Female          70000       2.0        Bachelors   

       Occupation Home Owner  Cars  Commute Distance         Region  Age  \
0        Clerical         No     1               1.0         Europe   33   
1        Clerical        Yes     0               1.0         Europe   37   
2    Professional         No     3               2.0         Europe   55   
3      Management        Yes     2               5.0        Pacific   47   
4  Skilled Manual         No     1               1.0  North America   38   

  Bike Buyer  
0        Yes  
1        Yes  
2         No  
3         No  
4        Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6997 entries, 0 to 6996
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                6996 non-null   float64
 1   Marital Status    6981 non-null   object 
 2   Gender            6968 non-null   object 
 3   Yearly Income     6997 non-null   int64  
 4   Children          6979 non-null   float64
 5   Education         6997 non-null   object 
 6   Occupation        6997 non-null   object 
 7   Home Owner        6997 non-null   object 
 8   Cars              6997 non-null   int64  
 9   Commute Distance  6968 non-null   float64
 10  Region            6997 non-null   object 
 11  Age               6997 non-null   int64  
 12  Bike Buyer        6997 non-null   object 
dtypes: float64(3), int64(3), object(7)
memory usage: 519.4+ KB


In [5]:
df.describe()

ID  Yearly Income     Children         Cars  \
count   6996.000000    6997.000000  6979.000000  6997.000000   
mean   17744.435249   57020.151493     1.111621     1.586823   
std     4337.428859   32080.449720     1.600912     1.146782   
min        2.000000       0.000000     0.000000     0.000000   
25%    14249.750000   30000.000000     0.000000     1.000000   
50%    17406.500000   60000.000000     0.000000     2.000000   
75%    20609.500000   70000.000000     2.000000     2.000000   
max    29476.000000  170000.000000     5.000000     4.000000   

       Commute Distance          Age  
count       6968.000000  6997.000000  
mean           4.210103    45.107332  
std            2.926211    11.916654  
min            1.000000    25.000000  
25%            1.000000    36.000000  
50%            4.000000    44.000000  
75%            6.000000    53.000000  
max           13.000000    96.000000

In [6]:
df.isnull().sum()

ID                   1
Marital Status      16
Gender              29
Yearly Income        0
Children            18
Education            0
Occupation           0
Home Owner           0
Cars                 0
Commute Distance    29
Region               0
Age                  0
Bike Buyer           0
dtype: int64

In [7]:
df["ID"].fillna(df["ID"].mean(), inplace=True)
marr_mode =df["Marital Status"].mode()
df["Marital Status"].fillna(marr_mode[0], inplace=True)
gender_mode = df["Gender"].mode()
df["Gender"].fillna(gender_mode[0], inplace=True)
df["Children"].fillna(df["Children"].mean(), inplace=True)
df["Commute Distance"].fillna(df["Commute Distance"].mean(), inplace=True)

In [8]:
df.isnull().sum()

ID                  0
Marital Status      0
Gender              0
Yearly Income       0
Children            0
Education           0
Occupation          0
Home Owner          0
Cars                0
Commute Distance    0
Region              0
Age                 0
Bike Buyer          0
dtype: int64

In [9]:
df.head()

ID Marital Status  Gender  Yearly Income  Children  \
0  22711.000000         Single    Male          30000       0.0   
1  13555.000000        Married  Female          40000       0.0   
2  17744.435249        Married    Male         160000       5.0   
3      2.000000         Single    Male         160000       0.0   
4  25410.000000        Married  Female          70000       2.0   

         Education      Occupation Home Owner  Cars  Commute Distance  \
0  Partial College        Clerical         No     1               1.0   
1  Graduate Degree        Clerical        Yes     0               1.0   
2  Partial College    Professional         No     3               2.0   
3  Graduate Degree      Management        Yes     2               5.0   
4        Bachelors  Skilled Manual         No     1               1.0   

          Region  Age Bike Buyer  
0         Europe   33        Yes  
1         Europe   37        Yes  
2         Europe   55         No  
3        Pacific   47         No  
4  North America   38        Yes

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
df["Bike Buyer"]= le.fit_transform(df["Bike Buyer"])

In [12]:
df.head()

ID Marital Status  Gender  Yearly Income  Children  \
0  22711.000000         Single    Male          30000       0.0   
1  13555.000000        Married  Female          40000       0.0   
2  17744.435249        Married    Male         160000       5.0   
3      2.000000         Single    Male         160000       0.0   
4  25410.000000        Married  Female          70000       2.0   

         Education      Occupation Home Owner  Cars  Commute Distance  \
0  Partial College        Clerical         No     1               1.0   
1  Graduate Degree        Clerical        Yes     0               1.0   
2  Partial College    Professional         No     3               2.0   
3  Graduate Degree      Management        Yes     2               5.0   
4        Bachelors  Skilled Manual         No     1               1.0   

          Region  Age  Bike Buyer  
0         Europe   33           1  
1         Europe   37           1  
2         Europe   55           0  
3        Pacific   47           0  
4  North America   38           1

In [13]:
x = df.iloc[:,:12].values
y = df.iloc[:,12].values
x

array([[22711.0, 'Single', 'Male', ..., 1.0, 'Europe', 33],
       [13555.0, 'Married', 'Female', ..., 1.0, 'Europe', 37],
       [17744.43524871355, 'Married', 'Male', ..., 2.0, 'Europe', 55],
       ...,
       [22823.0, 'Married', 'Female', ..., 1.0, 'Europe', 53],
       [22825.0, 'Single', 'Female', ..., 1.0, 'Europe', 54],
       [22826.0, 'Married', 'Male', ..., 2.0, 'Europe', 54]], dtype=object)

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [15]:
ct = ColumnTransformer([('oh', OneHotEncoder(), [1,2,5,6,7,10])], remainder = 'passthrough')
x_e = ct.fit_transform(x)

In [16]:
x_e

array([[0.0, 1.0, 0.0, ..., 1, 1.0, 33],
       [1.0, 0.0, 1.0, ..., 0, 1.0, 37],
       [1.0, 0.0, 0.0, ..., 3, 2.0, 55],
       ...,
       [1.0, 0.0, 1.0, ..., 2, 1.0, 53],
       [0.0, 1.0, 1.0, ..., 3, 1.0, 54],
       [1.0, 0.0, 0.0, ..., 3, 2.0, 54]], dtype=object)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train, y_test= train_test_split(x_e,y,test_size=0.3, random_state=0)

In [19]:
x_train.shape,x_test.shape,y_train.shape, y_test.shape

((4897, 25), (2100, 25), (4897,), (2100,))

In [20]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [21]:
log.fit(x_train, y_train)

LogisticRegression()

In [22]:
log_pred = log.predict(x_test)

In [23]:
log_pred

array([0, 0, 0, ..., 0, 0, 0])

In [24]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
accur = accuracy_score(y_test, log_pred)

In [27]:
accur

0.8571428571428571