In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("petrol_consumption.csv")

In [3]:
df.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Petrol_tax                    48 non-null     float64
 1   Average_income                48 non-null     int64  
 2   Paved_Highways                48 non-null     int64  
 3   Population_Driver_licence(%)  48 non-null     float64
 4   Petrol_Consumption            48 non-null     int64  
dtypes: float64(2), int64(3)
memory usage: 1.9 KB


In [5]:
df.describe()

Petrol_tax  Average_income  Paved_Highways  \
count   48.000000       48.000000       48.000000   
mean     7.668333     4241.833333     5565.416667   
std      0.950770      573.623768     3491.507166   
min      5.000000     3063.000000      431.000000   
25%      7.000000     3739.000000     3110.250000   
50%      7.500000     4298.000000     4735.500000   
75%      8.125000     4578.750000     7156.000000   
max     10.000000     5342.000000    17782.000000   

       Population_Driver_licence(%)  Petrol_Consumption  
count                     48.000000           48.000000  
mean                       0.570333          576.770833  
std                        0.055470          111.885816  
min                        0.451000          344.000000  
25%                        0.529750          509.500000  
50%                        0.564500          568.500000  
75%                        0.595250          632.750000  
max                        0.724000          968.000000

In [6]:
df.isnull().sum()

Petrol_tax                      0
Average_income                  0
Paved_Highways                  0
Population_Driver_licence(%)    0
Petrol_Consumption              0
dtype: int64

In [7]:
x = df.iloc[:,0:4].values

In [8]:
y = df.iloc[:,4].values

In [9]:
x.shape, y.shape #dataset size is very low. So, train_test_split is not done on the data

((48, 4), (48,))

In [10]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [11]:
lr.fit(x, y)

LinearRegression()

In [12]:
y_pred = lr.predict(x)

In [13]:
y_pred

array([523.23372749, 553.11530293, 578.10744578, 493.35625176,
       532.02892629, 433.55141589, 318.73259324, 491.50595563,
       489.02463498, 550.39466272, 500.48954932, 442.25333892,
       563.31260606, 566.0237744 , 638.06601138, 604.30550439,
       597.49738202, 596.40345112, 772.9677508 , 682.70972973,
       694.9794757 , 570.24033097, 415.07930617, 460.22150127,
       507.02812076, 531.91824029, 588.64881068, 612.08788703,
       558.02256272, 471.98285862, 566.90705013, 581.42200158,
       651.64983584, 613.86729832, 506.41719219, 716.82376287,
       647.28207972, 641.93375943, 717.64832948, 733.05284779,
       662.87034473, 633.06544672, 644.48932597, 556.96750449,
       713.79948278, 519.67828001, 670.3978699 , 569.438479  ])

In [14]:
y

array([541, 524, 561, 414, 410, 457, 344, 467, 464, 498, 580, 471, 525,
       508, 566, 635, 603, 714, 865, 640, 649, 540, 464, 547, 460, 566,
       577, 631, 574, 534, 571, 554, 577, 628, 487, 644, 640, 704, 648,
       968, 587, 699, 632, 591, 782, 510, 610, 524], dtype=int64)

In [15]:
from sklearn.metrics import r2_score

In [16]:
accur = r2_score(y, y_pred)

In [20]:
accur

0.6786867115698207

In [21]:
lr.predict([[8.9,9871,1834,0.675]])

array([308.01548596])