In [1]:
import numpy as np

In [2]:
data=[5,3,8,1,9]

In [3]:
arr=np.array(data)

In [4]:
arr

array([5, 3, 8, 1, 9])

In [5]:
data2=[[1,2,3,4],[5,6,7,8]]

In [6]:
arr2=np.array(data2)

In [7]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr1.dtype

NameError: name 'arr1' is not defined

In [10]:
arr2.dtype

dtype('int32')

In [11]:
arr.dtype

dtype('int32')

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(1,2)

TypeError: Cannot interpret '2' as a data type

In [14]:
np.zeros((1,2))

array([[0., 0.]])

In [15]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
arr.ndim

1

In [19]:
arr2.ndim

2

In [20]:
arr.empty()

AttributeError: 'numpy.ndarray' object has no attribute 'empty'

In [21]:
arr1=np.arra([1,2,3],dtype=np.float64)

AttributeError: module 'numpy' has no attribute 'arra'

In [22]:
arr1=np.array([1,2,3],dtype=np.float64)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr1

array([1., 2., 3.])

In [25]:
arr1=arr.astype(np.float64)

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr3=np.asarray(arr2)

In [28]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr3[1:3]

array([[5, 6, 7, 8]])

In [30]:
arra[1]

NameError: name 'arra' is not defined

In [31]:
arr3[1]

array([5, 6, 7, 8])

In [32]:
arr3[0]

array([1, 2, 3, 4])

In [33]:
arr3[0[1]]

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<ipython-input-33-61e01489e343>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  arr3[0[1]]


TypeError: 'int' object is not subscriptable

In [34]:
arr3_slice[1]

NameError: name 'arr3_slice' is not defined